language: node_js
node_js:
  - "8"
  - "10"
  - "12"
services:
  - "mongodb"
sudo: false
before_install:
  - npm i mongoose@^5.8.10
script:
  - npm run lint
  - npm run test-ci
after_success:
  - npm install coveralls@~2.11.0
  - npm run report-coverage
branches:
  only:
    - master
